---
kind: Service
apiVersion: v1
metadata:
  name: portfolio
spec:
  type: LoadBalancer
  selector:
    app: portfolio
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: nginx
        image: michaelbdavidson7/portfolio
        ports:
        - containerPort: 80
          protocol: TCP
